@startuml

Class CustomerCheck {
ID
ServerName
CheckName
TimeStamp
TableNumber
CheckTotal
PaymentMethod
LastFourCardDigits
ItemLog
}

Class Item {
ID
ItemName
Price
ItemCount
InStock
}

Class Modifier {
ID
ModifierName
}


@enduml