@startuml
!define DARKBLUE
!include https://github.com/Drakemor/RedDress-PlantUML.git



Class CustomerCheck {
ID
ServerName
CheckName
TimeStamp
TableNumber
CheckTotal
PaymentMethod
LastFourCardDigits
ItemLog
Getters()
Setters()
}

Class Item {
ID
ItemName
Price
ItemCount
InStock
Getters()
Setters()
}

Class Modifier {
ID
ModifierName
Price
Quantity
InStock
Getters()
Setters()
}


@enduml